name: social
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.4
  firebase_core: ^1.12.0
  firebase_auth: ^3.3.6
  google_sign_in: ^5.2.3
  hexcolor: ^2.0.6
  rive: ^0.8.1
  flutter_svg: ^1.0.3
  animations: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.4

flutter:

  uses-material-design: true

  assets:
   - assets/icons/
   - assets/animations/
