// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCr4mQeGO-CNdv6jRLXAMkjJU9bKX4xbVQ',
    appId: '1:852964369151:web:77f66e71d11924409722ca',
    messagingSenderId: '852964369151',
    projectId: 'social-75fc6',
    authDomain: 'social-75fc6.firebaseapp.com',
    storageBucket: 'social-75fc6.appspot.com',
    measurementId: 'G-P7LN7EE3K8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvI6eSeXJhQdHKVgSSYoZwkvzn4jQ1wAg',
    appId: '1:852964369151:android:03d6678c55444b119722ca',
    messagingSenderId: '852964369151',
    projectId: 'social-75fc6',
    storageBucket: 'social-75fc6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgI-7B6mke1Q_QVjI_eensCu2cuDGhyfQ',
    appId: '1:852964369151:ios:e8685d63413012a09722ca',
    messagingSenderId: '852964369151',
    projectId: 'social-75fc6',
    storageBucket: 'social-75fc6.appspot.com',
    androidClientId: '852964369151-5h1vsthsvd6essibmdp28ot1vkjn61ao.apps.googleusercontent.com',
    iosClientId: '852964369151-eou9l2p8vmrh3u7ibq317huok7kim97v.apps.googleusercontent.com',
    iosBundleId: 'com.matamar.social',
  );
}
